# Panther is a Cloud-Native SIEM for the Modern Security Team.
# Copyright (C) 2020 Panther Labs Inc
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

AWSTemplateFormatVersion: 2010-09-09
Description: >
  This stack configures Panther's real-time CloudWatch Event collection.
  It works by creating CloudWatch Event rules which feed to Panther's SQS Queue proxied by
  a local SNS topic in each region.

Parameters:
  MasterAccountId:
    Type: String
    Description: The AWS Account ID of the Panther deployment
  QueueArn:
    Type: String
    Description: The Panther SQS Queue Arn to receive CloudWatch Events via SNS

Resources:
  # SNS Topic, Policy, and Subscription to SQS

  PantherEventsTopic:
    Type: AWS::SNS::Topic

  TopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: CloudWatchEventsPublish
            Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sns:Publish
            Resource: !Ref PantherEventsTopic
          - Sid: CrossAccountSubscription
            Effect: Allow
            Principal:
              AWS: !Sub arn:${AWS::Partition}:iam::${MasterAccountId}:root
            Action: sns:Subscribe
            Resource: !Ref PantherEventsTopic
      Topics:
        - !Ref PantherEventsTopic

  QueueSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !Ref QueueArn
      Protocol: sqs
      RawMessageDelivery: true
      TopicArn: !Ref PantherEventsTopic

  CloudTrailRule:
    Type: AWS::Events::Rule
    Properties:
      Description: Collect CloudTrail API calls.
      EventPattern:
        detail-type:
          - AWS API Call via CloudTrail
      State: ENABLED
      Targets:
        - Arn: !Ref PantherEventsTopic
          Id: panther-collect-cloudtrail-events
