# Panther is a Cloud-Native SIEM for the Modern Security Team.
# Copyright (C) 2020 Panther Labs Inc
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

AWSTemplateFormatVersion: 2010-09-09
Description: >
  Panther IAM Role for creating and managing StackSets. The purpose of this role is to assume
  the execution IAM roles in each target account for configuring various Panther infrastructure.

Parameters:
  MasterAccountRegion:
    Type: String
    Default: ''

Conditions:
  UseCurrentRegion: !Equals ['', !Ref MasterAccountRegion]

Resources:
  CloudFormationStackSetAdminRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !If
        - UseCurrentRegion
        - !Sub PantherCloudFormationStackSetAdminRole-${AWS::Region}
        - !Sub PantherCloudFormationStackSetAdminRole-${MasterAccountRegion}
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AssumeRolesInTargetAccounts
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: sts:AssumeRole
                Resource: !If
                  - UseCurrentRegion
                  - !Sub arn:${AWS::Partition}:iam::*:role/PantherCloudFormationStackSetExecutionRole-${AWS::Region}
                  - !Sub arn:${AWS::Partition}:iam::*:role/PantherCloudFormationStackSetExecutionRole-${MasterAccountRegion}

Outputs:
  CloudFormationStackSetAdminRoleArn:
    Description: The Arn of the CloudFormation StackSet IAM Role for sending data to Panther.
    Value: !GetAtt CloudFormationStackSetAdminRole.Arn
